version: 0.2

phases:
  build:
    commands:
      - echo "===== DEBUG ====="
      - pwd
      - ls -la
      - echo "----- WEBSITE -----"
      - ls -la website || true
      - echo "----- FILES -----"
      - find . -maxdepth 3 -type f | sort